name: senn
channels:
  - Lyken
  - anaconda
  - ak_93
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.7
  - blas
  - torchvision
  - cuda100
  - pytorch
  - tensorboard
  - matplotlib
  - pandas
  - jupyter
  - scipy
  - scikit-learn
  - cudatoolkit=10.1

